{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nginx.fullname" . }}-ingress
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
spec:
  rules:
    - host: {{ .Values.ingress.host.name | quote}}
      http:
        paths:
          - path: {{ .Values.ingress.host.path }}
            pathType: {{ .Values.ingress.host.pathType }}
            backend:
              service:
                name: {{ .Values.ingress.host.serviceName }}
                port:
                  number: {{ .Values.ingress.host.servicePort }}
    {{- if .Values.ingress.extraHosts}}
    {{- range .Values.ingress.extraHosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ .serviceName }}
                port:
                  number: {{ .servicePort }}
          {{- end }}
    {{- end }}
    {{- end}}
  {{- if .Values.ingress.tls}}
  tls:
  {{- range .Values.ingress.tls }}
  - hosts:
    {{- range .hosts }}
    - {{ toYaml . }}
    {{- end}}
    secretName: {{ .secretName }}
  {{- end }}
  {{- end }}
{{- end }}