{{- if and .Values.ingress.enabled .Values.ingress.tls }}
apiVersion: v1
kind: Secret
metadata:
  name: sso-tls
  labels:
  {{- include "sso.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: |
  {{- .Files.Get "cert/ideas.li.crt" | nindent 4 }}
  tls.key: |
    {{- .Files.Get "cert/ideas.li.key" | nindent 4 }}
  {{- end }}