apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "activemq.pvcName" . }}
  {{- with .Values.persistentVolumeClaim.storageAnnotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.persistentVolumeClaim.accessModes }}
  accessModes:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.storageSize }}
  storageClassName: {{ .Values.persistentVolumeClaim.storageClassName }}