apiVersion: v1
kind: Service
metadata:
  name: {{ include "activemq.fullname" . }}
  labels:
    {{- include "activemq.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.activemq.tcp_port }}
      targetPort: tcp-port
      name: activemq
  selector:
    {{- include "activemq.selectorLabels" . | nindent 4 }}

